# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(db_index=True, max_length=100)),
                ('auth_desc', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(db_index=True, max_length=100)),
                ('cat_desc', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('pub_date', models.DateField(db_index=True)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Author')),
                ('category', models.ForeignKey(default='Adventure', on_delete=django.db.models.deletion.CASCADE, to='article.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ImageStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(db_index=True, max_length=100)),
                ('hero_img', models.ImageField(blank=True, null=True, upload_to='/home/binnyabraham/workspace/store/staticimages/')),
                ('hero_img_url', models.URLField(blank=True, null=True)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='/home/binnyabraham/workspace/store/staticimages/')),
                ('main_img_url', models.URLField(blank=True, null=True)),
                ('next_img', models.ImageField(blank=True, null=True, upload_to='/home/binnyabraham/workspace/store/staticimages/')),
                ('next_img_url', models.URLField(blank=True, null=True)),
                ('img_desc', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contentdetail',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ImageStore'),
        ),
    ]
