# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='auth_desc',
            new_name='author_desc',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='auth_name',
            new_name='author_name',
        ),
    ]
