# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160421_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_desc',
            new_name='category_desc',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='category_name',
        ),
    ]
