# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160421_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagestore',
            name='hero_img_url',
        ),
        migrations.RemoveField(
            model_name='imagestore',
            name='main_img_url',
        ),
        migrations.RemoveField(
            model_name='imagestore',
            name='next_img_url',
        ),
        migrations.AlterField(
            model_name='imagestore',
            name='hero_img',
            field=models.ImageField(blank=True, null=True, upload_to='/home/binnyabraham/workspace/store/static/images/'),
        ),
        migrations.AlterField(
            model_name='imagestore',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='/home/binnyabraham/workspace/store/static/images/'),
        ),
        migrations.AlterField(
            model_name='imagestore',
            name='next_img',
            field=models.ImageField(blank=True, null=True, upload_to='/home/binnyabraham/workspace/store/static/images/'),
        ),
    ]
