# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160421_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagestore',
            name='hero_img_url',
        ),
        migrations.RemoveField(
            model_name='imagestore',
            name='main_img_url',
        ),
        migrations.RemoveField(
            model_name='imagestore',
            name='next_img_url',
        ),
    ]
