# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20160421_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='/home/binnyabraham/workspace/store/static/upload//avatar/'),
        ),
        migrations.AlterField(
            model_name='imagestore',
            name='hero_img',
            field=models.ImageField(blank=True, null=True, upload_to='/home/binnyabraham/workspace/store/static/upload//images/'),
        ),
        migrations.AlterField(
            model_name='imagestore',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='/home/binnyabraham/workspace/store/static/upload//images/'),
        ),
        migrations.AlterField(
            model_name='imagestore',
            name='next_img',
            field=models.ImageField(blank=True, null=True, upload_to='/home/binnyabraham/workspace/store/static/upload//images/'),
        ),
    ]
