# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20160422_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='/home/binnyabraham/workspace/store/static/upload//category/'),
        ),
    ]
